import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import requests

from streamlit_lottie import st_lottie

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from datetime import datetime
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
# =====================================================

# pdf report
# =====================================================

from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime


def generate_pdf_report(patient, result):

    file_name = "Diabetes_Report.pdf"
    doc = SimpleDocTemplate(file_name)

    styles = getSampleStyleSheet()
    content = []

    # =========================
    # TITLE
    # =========================
    content.append(Paragraph(
        "MEDVISION AI - Diabetes Risk Report",
        styles['Title']
    ))
    content.append(Spacer(1, 20))

    # =========================
    # DATE
    # =========================
    content.append(Paragraph(
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        styles['Normal']
    ))
    content.append(Spacer(1, 20))

    # =========================
    # PATIENT DATA
    # =========================
    content.append(Paragraph("Patient Information", styles['Heading2']))
    content.append(Spacer(1, 10))

    for key, value in patient.items():
        content.append(Paragraph(f"{key}: {value}", styles['Normal']))

    content.append(Spacer(1, 20))

    # =========================
    # RESULT
    # =========================
    content.append(Paragraph("Prediction Result", styles['Heading2']))
    content.append(Spacer(1, 10))

    content.append(Paragraph(
        f"Prediction: {result['Prediction']}",
        styles['Normal']
    ))

    content.append(Paragraph(
        f"Risk Percentage: {result['Risk Percentage']}%",
        styles['Normal']
    ))

    content.append(Paragraph(
        f"Risk Level: {result['Risk Level']}",
        styles['Normal']
    ))

    content.append(Spacer(1, 20))

    # =========================
    # AI EXPLANATION
    # =========================
    content.append(Paragraph("AI Medical Explanation", styles['Heading2']))
    content.append(Spacer(1, 10))

    for item in result["Explanation"]:
        content.append(Paragraph(f"- {item}", styles['Normal']))

    content.append(Spacer(1, 20))

    # =========================
    # FOOTER
    # =========================
    content.append(Paragraph(
        "Generated by MedVision AI",
        styles['Italic']
    ))

    doc.build(content)

    return file_name
# =====================================================
# PAGE CONFIG
# =====================================================

st.set_page_config(
    page_title="MedVision AI",
    layout="wide"
)

# =====================================================
# LOTTIE
# =====================================================

def load_lottie(url):

    r = requests.get(url)

    if r.status_code != 200:
        return None

    return r.json()

animation = load_lottie(
    "https://assets4.lottiefiles.com/packages/lf20_yzoqyyqf.json"
)


# =====================================================
# CSS
# =====================================================




st.markdown("""
<style>

/* ===== BACKGROUND ===== */

.stApp {

    background:
    radial-gradient(circle at top left, #1e3a8a 0%, transparent 25%),
    radial-gradient(circle at bottom right, #6d28d9 0%, transparent 25%),
    #0b1120;

    color: #ffffff;
}

/* ===== HIDE STREAMLIT ===== */

#MainMenu {visibility:hidden;}
footer {visibility:hidden;}
header {visibility:hidden;}

/* ===== TEXT ===== */

html, body, p, div, span, label {

    color: #f8fafc !important;
}

h1,h2,h3,h4,h5,h6 {

    color: white !important;
}

/* ===== TITLE ===== */

.main-title {

    font-size: 75px;

    font-weight: 900;

    background: linear-gradient(
    90deg,
    #00E5FF,
    #7C3AED
    );

    -webkit-background-clip: text;

    -webkit-text-fill-color: transparent;

    letter-spacing: -2px;
}

.subtitle {

    color: #dbeafe !important;

    font-size: 24px;

    font-weight: 500;
}

/* ===== CARDS ===== */

.card {

    background: rgba(17,24,39,0.85);

    border: 1px solid rgba(255,255,255,0.08);

    border-radius: 24px;

    padding: 25px;

    margin-bottom: 20px;

    backdrop-filter: blur(20px);

    box-shadow:
    0 8px 32px rgba(0,0,0,0.25);

    transition: 0.3s;
}

.card:hover {

    transform: translateY(-5px);

    box-shadow:
    0 12px 40px rgba(0,229,255,0.15);
}

/* ===== BUTTON ===== */

.stButton > button {

    width: 100%;

    height: 58px;

    border: none;

    border-radius: 16px;

    background: linear-gradient(
    90deg,
    #00E5FF,
    #7C3AED
    );

    color: white;

    font-size: 20px;

    font-weight: bold;

    transition: 0.3s;
}

.stButton > button:hover {

    transform: scale(1.02);

    box-shadow:
    0 0 25px rgba(124,58,237,0.6);
}

/* ===== SLIDERS ===== */

.stSlider label {

    color: white !important;

    font-weight: 600;
}

/* ===== METRICS ===== */

.metric {

    text-align: center;

    font-size: 48px;

    font-weight: bold;

    color: #00E5FF;
}

/* ===== SUCCESS ===== */

.stSuccess {

    border-radius: 15px;
}

/* ===== ERROR ===== */

.stError {

    border-radius: 15px;
}

/* ===== PROGRESS BAR ===== */

.stProgress > div > div > div {

    background: linear-gradient(
    90deg,
    #00E5FF,
    #7C3AED
    );
}

/* ===== PLOTLY ===== */

.js-plotly-plot {

    border-radius: 20px;
}

</style>
""", unsafe_allow_html=True)

# =====================================================
# HERO
# =====================================================

left, right = st.columns([1.2,1])

with left:

    st.markdown(
        '<div class="main-title">MedVision AI</div>',
        unsafe_allow_html=True
    )

    st.markdown(
        '<div class="subtitle">Advanced AI Diabetes Detection System</div>',
        unsafe_allow_html=True
    )

    st.write("")

    st.markdown("""
    <div class="card">

    Intelligent healthcare platform powered by
    Machine Learning for advanced diabetes prediction.

    </div>
    """, unsafe_allow_html=True)



# =====================================================
# LOAD DATA


df = pd.read_csv("diabetes.csv")



# =====================================================
# CLEANING
# =====================================================

cols = [
    'Glucose',
    'BloodPressure',
    'SkinThickness',
    'Insulin',
    'BMI'
]

for col in cols:

    df[col] = df[col].replace(0, np.nan)

    df[col].fillna(
        df[col].median(),
        inplace=True
    )

# =====================================================
# FEATURES
# =====================================================

X = df.drop("Outcome", axis=1)

y = df["Outcome"]

# =====================================================
# SPLIT
# =====================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# =====================================================
# IMPUTER
# =====================================================

imputer = SimpleImputer(strategy='median')

X_train = imputer.fit_transform(X_train)

X_test = imputer.transform(X_test)

# =====================================================
# MODEL
# =====================================================

model = RandomForestClassifier()

model.fit(X_train, y_train)

accuracy = model.score(X_test, y_test)


# =====================================================

with right:

    st.markdown(f"""
    <div class="card">

    <h3>System Overview</h3>

    <br>

    <b>Dataset Records:</b> {len(df)}

    <br><br>

    <b>Model:</b> Random Forest

    <br><br>

    <b>Status:</b> Ready For Prediction

    </div>
    """, unsafe_allow_html=True)

# =====================================================
# INPUTS
# =====================================================

st.markdown("## Patient Information")

c1, c2, c3, c4 = st.columns(4)

with c1:

    pregnancies = st.slider(
        "Pregnancies",
        0,
        20,
        1
    )

    insulin = st.slider(
        "Insulin",
        0,
        900,
        80
    )

with c2:

    glucose = st.slider(
        "Glucose",
        0,
        300,
        120
    )

    bmi = st.slider(
        "BMI",
        0.0,
        70.0,
        25.0
    )

with c3:

    blood_pressure = st.slider(
        "Blood Pressure",
        0,
        200,
        70
    )

    dpf = st.slider(
        "DPF",
        0.0,
        3.0,
        0.5
    )

with c4:

    skin = st.slider(
        "Skin Thickness",
        0,
        100,
        20
    )

    age = st.slider(
        "Age",
        1,
        120,
        30
    )

predict = st.button("Analyze Patient")

# =====================================================
# PREDICTION
# =====================================================

if predict:

    # =========================
    # 1. Patient Input
    # =========================
    patient_df = pd.DataFrame([{
        'Pregnancies': pregnancies,
        'Glucose': glucose,
        'BloodPressure': blood_pressure,
        'SkinThickness': skin,
        'Insulin': insulin,
        'BMI': bmi,
        'DiabetesPedigreeFunction': dpf,
        'Age': age
    }])

    # =========================
    # 2. Prediction
    # =========================
    patient_processed = imputer.transform(patient_df)

    prediction = model.predict(patient_processed)[0]
    probability = model.predict_proba(patient_processed)[0][1]
    risk = round(probability * 100, 2)

    prediction_text = "Diabetic" if prediction == 1 else "Healthy"

    # =========================
    # 3. AI Explanation
    # =========================
    reasons = []

    if glucose > 140:
        reasons.append(f"High glucose level ({glucose})")

    if bmi > 30:
        reasons.append(f"High BMI ({bmi})")

    if age > 45:
        reasons.append(f"Age risk factor ({age})")

    if blood_pressure > 85:
        reasons.append(f"High blood pressure ({blood_pressure})")

    if insulin > 180:
        reasons.append(f"High insulin level ({insulin})")

    # =========================
    # 4. Risk Level
    # =========================
    if risk > 60:
        risk_level = "High"
    elif risk > 30:
        risk_level = "Medium"
    else:
        risk_level = "Low"

    # =========================
    # 5. RESULT DICT (IMPORTANT)
    # =========================
    result = {
        "Prediction": prediction_text,
        "Risk Percentage": risk,
        "Risk Level": risk_level,
        "Explanation": reasons
    }

    # =========================
    # 6. PDF GENERATION (IMPORTANT)
    # =========================
    pdf_file = generate_pdf_report(patient_df.to_dict("records")[0], result)

    # =========================
    # 7. UI OUTPUT
    # =========================
    st.markdown("""
    <div class="card">
    <h2>Prediction Result</h2>
    </div>
    """, unsafe_allow_html=True)

    if prediction == 1:
        st.error("High Diabetes Risk Detected")
    else:
        st.success("Patient Appears Healthy")

    st.write(f"## Risk Percentage: {risk}%")
    st.progress(int(risk))

    # =========================
    # 8. DOWNLOAD PDF (FIXED)
    # =========================
    with open(pdf_file, "rb") as f:
        st.download_button(
            label="Download PDF Report",
            data=f,
            file_name="Diabetes_Report.pdf",
            mime="application/pdf"
        )
    # =========================
    # ================================================

    # =================================================
    # METRICS
    # =================================================

    m1, m2, m3 = st.columns(3)

    with m1:

        st.markdown(f"""
        <div class="card">

        <div>Model Accuracy</div>

        <div class="metric">
        {round(accuracy*100,2)}%
        </div>

        </div>
        """, unsafe_allow_html=True)

    with m2:

        st.markdown("""
        <div class="card">

        <div>Analysis Time</div>

        <div class="metric">
        0.82s
        </div>

        </div>
        """, unsafe_allow_html=True)

    # =================================================
    # CHART
    # =================================================

    chart_data = pd.DataFrame({

        "Feature": [
            "Glucose",
            "Blood Pressure",
            "BMI",
            "Insulin",
            "Age"
        ],

        "Value": [
            glucose,
            blood_pressure,
            bmi,
            insulin,
            age
        ]
    })

    fig = px.bar(

        chart_data,

        x="Feature",

        y="Value",

        color="Value",

        text_auto=True
    )

    fig.update_layout(

        paper_bgcolor='rgba(0,0,0,0)',

        plot_bgcolor='rgba(0,0,0,0)',

        font_color='white'
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

# =================================================
# AI MEDICAL EXPLANATION
# =================================================

st.markdown("""
<div class="card">
<h2>AI Medical Explanation</h2>
</div>
""", unsafe_allow_html=True)

reasons = []

if glucose > 140:
    reasons.append(
        f"High Glucose Level ({glucose}) is increasing diabetes probability."
    )

if bmi > 30:
    reasons.append(
        f"BMI value ({bmi}) indicates obesity risk."
    )

if age > 45:
    reasons.append(
        f"Age ({age}) is considered a diabetes risk factor."
    )

if blood_pressure > 85:
    reasons.append(
        f"Blood Pressure ({blood_pressure}) is above normal range."
    )

if insulin > 180:
    reasons.append(
        f"Insulin level ({insulin}) may affect prediction."
    )

if len(reasons) == 0:

    st.success(
        "No significant medical risk factors detected."
    )

else:

    for reason in reasons:

        st.warning(reason)

# =================================================
# FEATURE IMPORTANCE
# =================================================

st.markdown("""
<div class="card">
<h2>Feature Importance</h2>
</div>
""", unsafe_allow_html=True)

importance = pd.DataFrame({

    "Feature": X.columns,

    "Importance": model.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

fig2 = px.bar(

    importance,

    x="Importance",

    y="Feature",

    orientation="h",

    text_auto=".2f",

    title="Most Influential Features"
)

fig2.update_layout(

    paper_bgcolor='rgba(0,0,0,0)',

    plot_bgcolor='rgba(0,0,0,0)',

    font_color='white'
)

st.plotly_chart(
    fig2,
    use_container_width=True
)